### ISSUE TITLE
Button to add sections in the sandwich menu

### ISSUE THREAD

**Issue by MrPhex** [Machriam/WariusWebWernwedienung#5]
I want a button labeled with a "+" sign to add new sections to the sandwich menu.

Clicking this button should open a modal window that contains an edittable section to set the button name and a create button.
Clicking the create button should create a new section containing no buttons.
There should be a button to delete these buttons as well.

There should always be one "main" section that cannot be deleted. 
All sections the are created by this button should be created as "sub" sections.

**Comment by MrPhex** [comment]
Analog a button should be available to remove the sections.

**Comment by Machriam** [comment]
What is the purpose of the Main-Section?
Even without any Sections you should be able to create new Sections?
