### ISSUE TITLE
Add buttons to sections of sandwich menu

### ISSUE THREAD

**Issue by MrPhex** [Machriam/WariusWebWernwedienung#6]
Depends on #5 
The modal window when clicking the "+" button to add new buttons should contain a dropdown listing all sections that are available in the sandwich menu. 
The new created button should only be shown in the selected section.

**Comment by Machriam** [comment]
Why would you want to create a Button for another Section, while being in another Section?
You could just go to the other Section and add the Button there. Click Efficiency?
